### ISSUE TITLE
Bug: open source file bug

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#568]
### Bug description

if you have a file-file pipeline, when you open the source file and write to it, you get an error
but if you only `echo` something into it... then it works fine

>  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x185ac22]
 goroutine 96 [running]:
github.com/conduitio/conduit-connector-file.(*Source).Read(0xc000171801?, {0x38209a0, 0xc0001035c0})
        /Users/mahahajja/go/pkg/mod/github.com/conduitio/conduit-connector-file@v0.1.0/source.go:57 +0xe2
github.com/conduitio/conduit-connector-sdk.(*sourcePluginAdapter).runRead(0xc0004fa8c0, {0x38209a0?, 0xc0001035c0?}, {0x3819ff8, 0xc0000d8940})
        /Users/mahahajja/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.2.1-0.20220622151135-47f1a8905435/source.go:163 +0xf8
github.com/conduitio/conduit-connector-sdk.(*sourcePluginAdapter).Run.func1()
        /Users/mahahajja/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.2.1-0.20220622151135-47f1a8905435/source.go:144 +0x72
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0001d31d0, 0xc00016b290?)
        /Users/mahahajja/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x36
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /Users/mahahajja/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xee

### Steps to reproduce

1. create a file to file pipeline
2. open the source file and write to it "not from the cmd"
3. an error will occur

### Version

v0.3.0-nightly.20220809-2-gc8b4e52-dirty darwin/amd64

**Comment by hariso** [comment]
@maha-hajja Is the source file initially empty? When you say:
> when you open the source file and write to it, you get an error
but if you only echo something into it... then it works fine

so you open the file using an editor, and then you get the nil dereference, but when you use `echo`, it works as expected?

**Comment by maha-hajja** [comment]
@hariso the source file could be initially empty or not.. either way if you open it from an editor and add something, the pipeline would fail
