### ISSUE TITLE
The conduit is crashed when use Source connectors with the different configuration

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#611]
Note: [bug reproduced rarely]

Logs:
2022-05-25T13:07:47+00:00 INF source connector plugin successfully started component=connector.Source connector_id=053d525d-91cd-4864-8342-d86da05f755c
2022-05-25T13:07:47+00:00 INF source connector plugin successfully started component=connector.Source connector_id=90b4025e-94e3-4f0e-8716-7198b153f5de
2022-05-25T13:07:48+00:00 INF request processed duration=0.002875 grpc_method=/api.v1.PipelineService/GetPipeline grpc_status_code=OK http_endpoint="GET /v1/pipelines/42bf9de2-e513-41bf-b2d5-d4cfbb11dbe0" request_id=20ab6c5b-a580-454a-95a1-f590079470f7
panic: tried to get error cause of Ack, read a record instead, this is a bug! original error: EOF
goroutine 207 [running]:
github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*sourcePluginClient).ackErrorCause(0x140001d43c0, {0x10705eb98?, 0x14000192110})
/Users/serhii/conduit/pkg/plugin/standalone/v1/source.go:138 +0x110
github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*sourcePluginClient).Ack(0x140001d43c0, {0x0?, 0x0?}, {0x140006815a0, 0x8, 0x8})
/Users/serhii/conduit/pkg/plugin/standalone/v1/source.go:118 +0xdc
github.com/conduitio/conduit/pkg/connector.(*source).Ack(0x14006eae6e0, {0x1070721b0, 0x1400059c570}, {0x140006815a0, 0x8, 0x8})
/Users/serhii/conduit/pkg/connector/source.go:218 +0x80
github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run.func4(0x140002934a0, 0x140005d5bc0)
/Users/serhii/conduit/pkg/pipeline/stream/source.go:120 +0xc4
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1(0x10?, {0x140004c4120?, 0x1400642eec8?, {0x0?, 0x0?}}, 0x1400046c270)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:178 +0xd4
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1081b8a68?, {0x1400621a3c0?, 0x407ce00000000000?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1.1(0x30?)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:179 +0x38
github.com/conduitio/conduit/pkg/pipeline/stream.(*MetricsNode).Run.func1(0x140002934a0, 0x140005d5b90)
/Users/serhii/conduit/pkg/pipeline/stream/metrics.go:63 +0xa8
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1(0x140005fbaa0?, {0x0?, 0x140005fba40?, {0x0?, 0x0?}}, 0x1400046c288)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:178 +0xd4
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1?, {0x107033b01?, 0x106e06ee0?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).notifyStatusHandlers(0x140002934a0, 0x106e06ee0?, {0x0, 0x0})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:221 +0x108
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).Ack.func1()
/Users/serhii/conduit/pkg/pipeline/stream/message.go:239 +0x34
sync.(*Once).doSlow(0x1400642f2c8?, 0x104b14f50?)
/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:59
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).Ack(0x140002934a0)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:238 +0x5c
github.com/conduitio/conduit/pkg/pipeline/stream.(*FanoutNode).Run.func2.1(0x100010000000001?)
/Users/serhii/conduit/pkg/pipeline/stream/fanout.go:85 +0x13c
github.com/conduitio/conduit/pkg/pipeline/stream.(*FanoutNode).wrapAckHandler.func1(0x1?, 0x140005d5b60)
/Users/serhii/conduit/pkg/pipeline/stream/fanout.go:151 +0x38
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1(0x1400642f308?, {0x104b08574?, 0x1400642f308?, {0x0?, 0x0?}}, 0x1070578b8)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:178 +0xd4
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1400642f368?, {0x104b08154?, 0x1400642f388?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterNackHandler.func1(0x0?, {0x106ed5fe0?, 0x1400642f3b8?, {0x0?, 0x0?}}, 0x1?)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:190 +0xf8
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1400642f408?, {0x104d88108?, 0x107ae3b80?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterDropHandler.func1(0x10?, {0x140004c4120?, 0x1400642f458?, {0x0?, 0x0?}}, 0x407ce00000000000?)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:205 +0x100
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1081b8a68?, {0x1400621a3c0?, 0x407ce00000000000?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1.1(0x30?)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:179 +0x38
github.com/conduitio/conduit/pkg/pipeline/stream.(*MetricsNode).Run.func1(0x1400650a0f0, 0x140005d5b30)
/Users/serhii/conduit/pkg/pipeline/stream/metrics.go:63 +0xa8
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterAckHandler.func1(0x1400620f140?, {0x0?, 0x1400620f0e0?, {0x0?, 0x0?}}, 0x14006b69338)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:178 +0xd4
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).RegisterStatusHandler.func1(0x1400613c2a0?, {0x14005de9748?, 0x14005de9808?, {0x0?, 0x0?}})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:166 +0x34
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).notifyStatusHandlers(0x1400650a0f0, 0x104b3d1b4?, {0x0, 0x0})
/Users/serhii/conduit/pkg/pipeline/stream/message.go:221 +0x108
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).Ack.func1()
/Users/serhii/conduit/pkg/pipeline/stream/message.go:239 +0x34
sync.(*Once).doSlow(0x6c?, 0x1f4?)
/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:59
github.com/conduitio/conduit/pkg/pipeline/stream.(*Message).Ack(0x1400650a0f0)
/Users/serhii/conduit/pkg/pipeline/stream/message.go:238 +0x5c
github.com/conduitio/conduit/pkg/pipeline/stream.(*AckerNode).handleAck(0x140005a9770?, 0x1400650a0f0, {0x0?, 0x0?})
/Users/serhii/conduit/pkg/pipeline/stream/acker.go:152 +0x1bc
github.com/conduitio/conduit/pkg/pipeline/stream.(*AckerNode).Run(0x140003965a0, {0x107072108, 0x14005ecf580})
/Users/serhii/conduit/pkg/pipeline/stream/acker.go:116 +0x394
github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func1()
/Users/serhii/conduit/pkg/pipeline/lifecycle.go:372 +0x180
gopkg.in/tomb%2ev2.(*Tomb).run(0x140006861e0, 0x0?)
/Users/serhii/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x34
created by gopkg.in/tomb%2ev2.(*Tomb).Go
/Users/serhii/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0x130

**Comment by uchennakevinm1** [comment]
this panic is not apart of the code.
